### ISSUE TITLE
Page shows up as "Invalid Date"

### ISSUE THREAD

**Issue by Khepu** [devnyxie/nigiri#11]
Hello!

I have removed all sample pages from my fork and replaced them with just one file titled `2024-02-25.md` but on a fresh deployment it shows up as "Invalid Date" on the interface. I am pretty sure it's valid. Any advice?

**Comment by devnyxie** [comment]
Hey there! It looks like you forgot to include a starting point for your blog post.

Ensure to add the following to each of your blog posts:

```
--- 
title: 'Title'
excerpt: 'Short Description'
date: 'ISO' 
---
```

That being said, I believe it's essential to implement proper error handling to prevent posts without a title and date from being included. Will do 😉

**Comment by Khepu** [comment]
Yes, that solved it! Thanks :D
